import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:provider/provider.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/localization/app_localizations.dart';
import '../../../../shared/context/business_context.dart';

import '../../../../shared/widgets/app_text_field.dart';
import '../../../../shared/widgets/app_button.dart';
import '../../../location/presentation/bloc/location_bloc.dart';
import '../../../location/presentation/bloc/location_event.dart';
import '../../../location/presentation/bloc/location_state.dart';
import '../../domain/entities/employee_entity.dart';
import '../bloc/employee_bloc.dart';
import '../bloc/employee_event.dart';
import '../bloc/employee_state.dart';

class AddEmployeePage extends StatefulWidget {
  const AddEmployeePage({super.key});

  @override
  State<AddEmployeePage> createState() => _AddEmployeePageState();
}

class _AddEmployeePageState extends State<AddEmployeePage> {
  final TextEditingController _searchController = TextEditingController();
  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _phoneController = TextEditingController();

  final List<String> _selectedLocationIds = [];
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    // Load locations if not loaded
    context.read<LocationBloc>().add(const LoadLocationsRequested());
  }

  @override
  void dispose() {
    _searchController.dispose();
    _nameController.dispose();
    _emailController.dispose();
    _phoneController.dispose();
    super.dispose();
  }

  void _onSave() {
    if (_nameController.text.isEmpty || _phoneController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(AppLocalizations.of(context).translate('common.required_field')),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    final businessId = Provider.of<BusinessContext>(context, listen: false).currentBusinessId ?? '';

    final employee = EmployeeEntity(
      id: '', // Will be generated by Mock Repo
      name: _nameController.text.trim(),
      email: _emailController.text.trim(),
      phone: _phoneController.text.trim(),
      status: EmployeeStatus.pending,
      assignedBusinessId: businessId,
      assignedLocationIds: _selectedLocationIds,
    );

    context.read<EmployeeBloc>().add(AddEmployeeRequested(businessId: businessId, employee: employee));
  }

  @override
  Widget build(BuildContext context) {
    final t = AppLocalizations.of(context);
    final theme = Theme.of(context);

    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        title: Text(t.translate('employee.add_employee')), 
        centerTitle: true, 
        backgroundColor: AppColors.white, 
        foregroundColor: AppColors.textPrimary,
        iconTheme: const IconThemeData(color: Colors.black),
        systemOverlayStyle: SystemUiOverlayStyle.dark,
      ),
      body: SafeArea(
        child: BlocListener<EmployeeBloc, EmployeeState>(
          listener: (context, state) {
            if (state is EmployeeActionInProgress) {
              setState(() => _isLoading = true);
            } else {
              setState(() => _isLoading = false);
              
              if (state is EmployeeActionSuccess) {
                Navigator.pop(context);
              } else if (state is EmployeeFailure) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text(state.message), backgroundColor: AppColors.error),
                );
              }
            }
          },
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Info Section
                Text(
                  t.translate('employee.personal_info'),
                  style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 16),

                // Search Input (Mock UI only for visual, actually they can just type email/phone below)
                AppTextField(
                  controller: _searchController,
                  hintText: t.translate('employee.email_or_phone_hint'),
                  prefixIcon: const Icon(Icons.search),
                ),
                const SizedBox(height: 16),

                AppTextField(
                  controller: _nameController,
                  hintText: t.translate('employee.name_label'),
                  label: t.translate('employee.name_label'),
                  prefixIcon: const Icon(Icons.person_outline),
                ),
                const SizedBox(height: 12),

                AppTextField(
                  controller: _emailController,
                  hintText: t.translate('employee.email_label'),
                  label: t.translate('employee.email_label'),
                  prefixIcon: const Icon(Icons.email_outlined),
                ),
                const SizedBox(height: 12),

                AppTextField(
                  controller: _phoneController,
                  hintText: t.translate('employee.phone_label'),
                  label: t.translate('employee.phone_label'),
                  prefixIcon: const Icon(Icons.phone_outlined),
                  keyboardType: TextInputType.phone,
                ),
                
                const SizedBox(height: 24),

                // Warehouse Section
                Text(
                  t.translate('employee.warehouse_permission'),
                  style: theme.textTheme.titleMedium?.copyWith(fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 16),

                Container(
                  decoration: BoxDecoration(
                    color: Colors.white,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: AppColors.divider),
                  ),
                  child: BlocBuilder<LocationBloc, LocationState>(
                    builder: (context, state) {
                      if (state is LocationsLoaded) {
                        return ListView.separated(
                          shrinkWrap: true,
                          physics: const NeverScrollableScrollPhysics(),
                          itemCount: state.locations.length,
                          separatorBuilder: (_, __) => const Divider(height: 1, color: AppColors.divider),
                          itemBuilder: (context, index) {
                            final location = state.locations[index];
                            final isSelected = _selectedLocationIds.contains(location.id);

                            return CheckboxListTile(
                              title: Text(
                                location.name,
                                style: theme.textTheme.bodyLarge,
                              ),
                              value: isSelected,
                              activeColor: AppColors.primary,
                              controlAffinity: ListTileControlAffinity.leading,
                              onChanged: (value) {
                                setState(() {
                                  if (value == true) {
                                    _selectedLocationIds.add(location.id);
                                  } else {
                                    _selectedLocationIds.remove(location.id);
                                  }
                                });
                              },
                            );
                          },
                        );
                      }
                      return const Padding(
                        padding: EdgeInsets.all(16.0),
                        child: Center(child: CircularProgressIndicator()),
                      );
                    },
                  ),
                ),
                
                const SizedBox(height: 32),
              ],
            ),
          ),
        ),
      ),
      bottomNavigationBar: SafeArea(
        child: Padding(
          padding: const EdgeInsets.fromLTRB(16.0, 16.0, 16.0, 32.0),
          child: AppButton(
            onPressed: _isLoading ? null : _onSave,
            label: t.translate('common.confirm'),
            isLoading: _isLoading,
            isFullWidth: true,
          ),
        ),
      ),
    );
  }
}
